# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160117_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to=b''),
        ),
    ]
