# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160106_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('avaliable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='editor_choice',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Editor'),
        ),
    ]
